name: Update README projects

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 7 * * *"   # ежедневный запуск: 07:17 UTC
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # нужно, чтобы коммитить изменения README
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update README projects section
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Geist-dev          # ← твой GitHub ник
          MAX_REPOS: "10"               # ← сколько репозиториев показывать
          FEATURED_TOPIC: featured     # ← репо с этим topic идут первыми
          EXCLUDE_FORKS: "true"        # ← скрывать форки
          EXCLUDE_ARCHIVED: "true"     # ← скрывать архивные
        run: |
          python scripts/update_readme.py
      - name: Debug tree
        run: |
          pwd
          ls -la
          ls -la scripts || true
          git ls-files | sed -n '1,120p'


      - name: Commit changes (if any)
        run: |
          if git diff --quiet; then
            echo "No changes"
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: auto-update projects section"
            git push
          fi
